backend:
  name: git-gateway
  branch: master

media_folder: "_site/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "index"
    label: "Index"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Featured Alt Text", name: "featuredAltText", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "one"
    label: "One"
    folder: "one"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/one-article.njk" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Featured Alt Text", name: "featuredAltText", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "two"
    label: "Two"
    folder: "two"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/three-article.njk" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Featured Alt Text", name: "featuredAltText", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "three"
    label: "Three"
    folder: "three"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/three-article.njk" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Featured Alt Text", name: "featuredAltText", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
